# Builds the project
name: Android Feature Branch CI

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK 1.17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew build